name: Preprocessing Otomatis

on:
  push:
    branches:
      - main

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r preprocessing/requirements.txt

      - name: Run preprocessing script
        run: |
          python preprocessing/automate_NamaSiswa.py \
            --input telco_raw/WA_Fn-UseC_-Telco-Customer-Churn.csv \
            --output preprocessing/telco_preprocessing

      - name: Upload hasil preprocessing sebagai artifact
        uses: actions/upload-artifact@v4
        with:
          name: telco_preprocessing
          path: preprocessing/telco_preprocessing/
